const NOTES={C4:{id:'C4',name:'C',step:-2,freq:261.63,word:'balcony'},D4:{id:'D4',name:'D',step:-1,freq:293.66,word:'doorstep'},E4:{id:'E4',name:'E',step:0,freq:329.63,word:'Every'},F4:{id:'F4',name:'F',step:1,freq:349.23,word:'Fairy'},G4:{id:'G4',name:'G',step:2,freq:392,word:'Good'},A4:{id:'A4',name:'A',step:3,freq:440,word:'Always'},B4:{id:'B4',name:'B',step:4,freq:493.88,word:'Butterfly'},C5:{id:'C5',name:'C',step:5,freq:523.25,word:'Collects'},D5:{id:'D5',name:'D',step:6,freq:587.33,word:'Does'},E5:{id:'E5',name:'E',step:7,freq:659.25,word:'Emeralds'},F5:{id:'F5',name:'F',step:8,freq:698.46,word:'Fly'},G5:{id:'G5',name:'G',step:9,freq:783.99,word:'garden'}};
const LINE_NOTES=['E4','G4','B4','D5','F5'];
const SPACE_NOTES=['F4','A4','C5','E5'];
const STAFF_NOTES=['E4','F4','G4','A4','B4','C5','D5','E5','F5'];
const ALL_NOTES=['C4','D4','E4','F4','G4','A4','B4','C5','D5','E5','F5','G5'];
const LETTERS=['C','D','E','F','G','A','B'];
const LESSONS=[{id:'staff',title:'The Magic Staff',emoji:'🌈',blurb:'Five lines. Four spaces. Notes live on both.',pool:STAFF_NOTES,teach:'A note on a line hugs the line. A note in a space sits between two lines.'},{id:'lines',title:'Line Notes',emoji:'🦋',blurb:'Every Good Butterfly Does Fly.',pool:LINE_NOTES,teach:'Bottom line to top line: E G B D F. Every Good Butterfly Does Fly.'},{id:'spaces',title:'Space Notes',emoji:'✨',blurb:'Fairy Always Collects Emeralds.',pool:SPACE_NOTES,teach:'The four spaces spell FACE. Fairy Always Collects Emeralds.'},{id:'middle',title:'Middle C Balcony',emoji:'👑',blurb:'Middle C has her own little line.',pool:['C4','D4','E4','F4','G4'],teach:'Middle C sits on a short line under the staff, like a princess on a balcony.'}];
const SONGS=[{id:'twinkle',title:'Twinkle, Twinkle',notes:['C4','C4','G4','G4','A4','A4','G4','F4','F4','E4','E4','D4','D4','C4']},{id:'mary',title:'Mary Had a Little Lamb',notes:['E4','D4','C4','D4','E4','E4','E4','D4','D4','D4','E4','G4','G4','E4','D4','C4','D4','E4','E4','E4','E4','D4','D4','E4','D4','C4']}];
const ITEMS=[{id:'clip',name:'Rainbow Butterfly Clip',emoji:'🦋',rare:'common',about:'A glitter claw clip for castle hair days.'},{id:'bow',name:'Glitter Hair Bow',emoji:'🎀',rare:'common',about:'Pops on a ponytail or a music stand.'},{id:'bracelet',name:'Friendship Bead Bracelet',emoji:'📿',rare:'common',about:'Rainbow beads, the kind friends trade.'},{id:'cloud',name:'Cloud Plush Buddy',emoji:'☁️',rare:'common',about:'A squishy cloud that fits in a pocket.'},{id:'crown',name:'Flower Crown',emoji:'🌸',rare:'common',about:'Pink and lavender blossoms, no thorns.'},{id:'locket',name:'Heart Locket',emoji:'💗',rare:'common',about:'Opens to hold a tiny butterfly.'},{id:'stickers',name:'Star Sticker Sheet',emoji:'⭐',rare:'common',about:'Peel-and-stick sparkles for everything.'},{id:'slippers',name:'Unicorn Slippers',emoji:'🦄',rare:'common',about:'Soft slippers for quiet practice.'},{id:'tumbler',name:'Rainbow Cup Charm',emoji:'🥤',rare:'common',about:'A dangling charm for a favorite cup.'},{id:'lumi',name:'Lumi Bag Charm',emoji:'🩷',rare:'rare',about:'A peach plush buddy with sparkle eyes. Clips on a bag.'},{id:'halo',name:'Halo Fruit Pal',emoji:'😇',rare:'rare',about:'A tiny angel friend in a fruit hat.'},{id:'wand',name:'Starlight Wand',emoji:'🌟',rare:'rare',about:'Taps the right note and glows.'},{id:'tiara',name:'Glitter Tiara',emoji:'👑',rare:'rare',about:'Melody practice crown.'},{id:'cape',name:'Butterfly Wing Cape',emoji:'🧚',rare:'rare',about:'Wings for spinning between songs.'},{id:'ring',name:'Rainbow Gem Ring',emoji:'💍',rare:'rare',about:'One gem for every line note.'},{id:'purse',name:'Mini Purse Charm',emoji:'👛',rare:'rare',about:'A pearl purse that holds one star.'},{id:'bunny',name:'Jelly Bunny Pal',emoji:'🐰',rare:'rare',about:'A floppy bunny from the surprise box.'},{id:'fairy',name:'Secret Sparkle Fairy',emoji:'🧚‍♀️',rare:'secret',about:'The rarest friend in the chest. She only appears sometimes.'}];
const CHEST_COST=8;
const state=load();
let audioCtx=null,quiz=null,song=null;
function load(){try{const saved=JSON.parse(localStorage.getItem('note-castle-v1')||'null');if(saved&&saved.items)return saved;}catch(e){}return{name:'Princess',stars:0,correct:0,lessons:{},songs:{},items:[],opened:0};}
function save(){localStorage.setItem('note-castle-v1',JSON.stringify(state));paintStars();}
function paintStars(){document.querySelectorAll('[data-stars]').forEach(el=>el.textContent='⭐ '+state.stars);const hello=document.getElementById('hello');if(hello)hello.textContent=state.name+"'s castle";}
function unlockAudio(){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;if(!audioCtx)audioCtx=new Ctx();if(audioCtx.state==='suspended')audioCtx.resume();}
function playFreq(freq,dur){unlockAudio();if(!audioCtx)return;const t=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.22,t+0.03);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+0.05);}
function speak(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=0.92;u.pitch=1.15;window.speechSynthesis.speak(u);}
function show(id){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(btn=>btn.classList.toggle('on',btn.dataset.screen===id));window.scrollTo(0,0);}
function staffSVG(noteId){const note=NOTES[noteId],top=36,gap=18,bottom=top+gap*4,y=bottom-note.step*(gap/2),cx=188,stemUp=note.step<4;const lines=[0,1,2,3,4].map(i=>'<line x1="54" y1="'+(top+i*gap)+'" x2="280" y2="'+(top+i*gap)+'" stroke="#c9a0d8" stroke-width="2"/>').join('');let ledger='';if(note.step<=-2||note.step>=10)ledger='<line x1="'+(cx-18)+'" y1="'+y+'" x2="'+(cx+18)+'" y2="'+y+'" stroke="#c9a0d8" stroke-width="2"/>';const stem=stemUp?'<line x1="'+(cx+10)+'" y1="'+y+'" x2="'+(cx+10)+'" y2="'+(y-42)+'" stroke="#6b3d86" stroke-width="2.4"/>':'<line x1="'+(cx-10)+'" y1="'+y+'" x2="'+(cx-10)+'" y2="'+(y+42)+'" stroke="#6b3d86" stroke-width="2.4"/>';return '<svg viewBox="0 0 320 168" role="img" aria-label="Note '+note.name+'"><text x="18" y="112" font-size="78" fill="#e2569a">𝄞</text>'+lines+ledger+'<ellipse cx="'+cx+'" cy="'+y+'" rx="12" ry="8.5" fill="#6b3d86" transform="rotate(-18 '+cx+' '+y+')"/>'+stem+'</svg>';}
function shuffle(list){const copy=list.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function choicesFor(noteId){const correct=NOTES[noteId].name;return shuffle([correct].concat(shuffle(LETTERS.filter(l=>l!==correct)).slice(0,3)));}
function hintFor(noteId){if(LINE_NOTES.includes(noteId))return NOTES[noteId].name+' is a line note. Every Good Butterfly Does Fly.';if(SPACE_NOTES.includes(noteId))return NOTES[noteId].name+' is a space note. Fairy Always Collects Emeralds.';if(noteId==='C4')return 'Middle C sits on her own little balcony line.';return 'This note is '+NOTES[noteId].name+'.';}
function startQuiz(pool,title,onDone){quiz={pool:pool.slice(),title,left:Math.min(6,pool.length),score:0,tries:0,onDone};show('play');document.getElementById('play-title').textContent=title;nextQuestion();}
function nextQuestion(){if(quiz.left<=0){finishQuiz();return;}const noteId=quiz.pool[Math.floor(Math.random()*quiz.pool.length)];quiz.noteId=noteId;quiz.tries=0;quiz.left--;document.getElementById('staff').innerHTML=staffSVG(noteId);document.getElementById('feedback').textContent='What letter is this note?';const box=document.getElementById('choices');box.innerHTML='';choicesFor(noteId).forEach(letter=>{const btn=document.createElement('button');btn.className='choice';btn.textContent=letter;btn.addEventListener('click',()=>answer(letter,btn));box.appendChild(btn);});playFreq(NOTES[noteId].freq,0.55);}
function answer(letter,btn){const note=NOTES[quiz.noteId];if(letter===note.name){btn.classList.add('good');quiz.score++;const bonus=quiz.tries===0?2:1;state.stars+=bonus;state.correct++;save();document.getElementById('feedback').textContent='Yes! '+note.name+' for '+note.word+'. +'+bonus+' stars';speak('Yes! '+note.name);document.querySelectorAll('.choice').forEach(el=>el.disabled=true);setTimeout(nextQuestion,900);}else{quiz.tries++;btn.classList.add('bad');btn.disabled=true;document.getElementById('feedback').textContent=hintFor(quiz.noteId);speak('Try again. '+hintFor(quiz.noteId));}}
function finishQuiz(){const earned=quiz.score>=5;document.getElementById('feedback').textContent=earned?'Castle cheers! '+quiz.score+' notes sparkled.':'Lovely try. '+quiz.score+' notes found.';document.getElementById('choices').innerHTML='';if(quiz.onDone)quiz.onDone(quiz.score);if(earned)setTimeout(()=>openChest(true),700);}
function renderLessons(){const box=document.getElementById('lessons');box.innerHTML='';LESSONS.forEach(lesson=>{const done=state.lessons[lesson.id];const btn=document.createElement('button');btn.className='lesson'+(done?' done':'');btn.innerHTML='<div class="badge">'+lesson.emoji+'</div><div><strong>'+lesson.title+'</strong><span class="lede">'+lesson.blurb+(done?' · crown earned':'')+'</span></div>';btn.addEventListener('click',()=>openLesson(lesson));box.appendChild(btn);});}
function openLesson(lesson){show('learn-detail');document.getElementById('learn-title').textContent=lesson.title;document.getElementById('learn-teach').textContent=lesson.teach;const sample=lesson.pool[0];document.getElementById('learn-staff').innerHTML=staffSVG(sample);document.getElementById('learn-hear').onclick=()=>{playFreq(NOTES[sample].freq,0.7);speak(NOTES[sample].name+', '+NOTES[sample].word);};document.getElementById('learn-go').onclick=()=>startQuiz(lesson.pool,lesson.title,score=>{if(score>=4){state.lessons[lesson.id]=true;state.stars+=3;save();}renderLessons();});}
function renderSongs(){const box=document.getElementById('songs');box.innerHTML='';SONGS.forEach(item=>{const done=state.songs[item.id];const btn=document.createElement('button');btn.className='lesson'+(done?' done':'');btn.innerHTML='<div class="badge">🎵</div><div><strong>'+item.title+'</strong><span class="lede">'+item.notes.length+' notes'+(done?' · song crown':'')+'</span></div>';btn.addEventListener('click',()=>startSong(item));box.appendChild(btn);});}
function startSong(item){song={...item,i:0,misses:0};show('song');document.getElementById('song-title').textContent=item.title;paintSong();}
function paintSong(){const noteId=song.notes[song.i];document.getElementById('song-staff').innerHTML=staffSVG(noteId);document.getElementById('song-feedback').textContent='Tap the letter for this note.';const pips=document.getElementById('pips');pips.innerHTML='';song.notes.forEach((id,index)=>{const pip=document.createElement('div');pip.className='pip'+(index<song.i?' did':index===song.i?' now':'');pip.textContent=NOTES[id].name;pips.appendChild(pip);});playFreq(NOTES[noteId].freq,0.45);document.querySelectorAll('.key').forEach(key=>key.onclick=()=>songAnswer(key.dataset.letter));}
function songAnswer(letter){const note=NOTES[song.notes[song.i]];if(letter!==note.name){song.misses++;document.getElementById('song-feedback').textContent='Listen again. '+hintFor(note.id);playFreq(note.freq,0.45);return;}state.stars++;state.correct++;save();song.i++;if(song.i>=song.notes.length){state.songs[song.id]=true;state.stars+=4;save();document.getElementById('song-feedback').textContent='Song complete! The butterflies are dancing.';speak('Beautiful! Song complete.');renderSongs();setTimeout(()=>openChest(true),800);return;}paintSong();}
function unowned(){return ITEMS.filter(item=>!state.items.includes(item.id));}
function drawItem(){const left=unowned();if(!left.length)return null;const roll=Math.random();let pool=left.filter(item=>item.rare==='common');if(roll>0.72)pool=left.filter(item=>item.rare==='rare');if(roll>0.93)pool=left.filter(item=>item.rare==='secret');if(!pool.length)pool=left;return pool[Math.floor(Math.random()*pool.length)];}
function openChest(free){if(!free&&state.stars<CHEST_COST){openSheet('Not enough stars yet','Play a few more notes. A chest costs '+CHEST_COST+' stars.','⭐');return;}if(!free)state.stars-=CHEST_COST;state.opened++;const item=drawItem();if(!item){state.stars+=3;save();openSheet('The chest is giggling','You already found every charm. Here are 3 bonus stars.','🌈');return;}state.items.push(item.id);save();openSheet(item.name,item.about+' She is a '+item.rare+' charm.',item.emoji);speak('You found '+item.name);renderCollection();}
function openSheet(title,text,emoji){document.getElementById('sheet-title').textContent=title;document.getElementById('sheet-text').textContent=text;document.getElementById('sheet-emoji').textContent=emoji;document.getElementById('modal').classList.add('show');}
function renderCollection(){const box=document.getElementById('collection');box.innerHTML='';document.getElementById('owned').textContent=state.items.length+' / '+ITEMS.length+' charms';ITEMS.forEach(item=>{const have=state.items.includes(item.id);const card=document.createElement('div');card.className='item'+(have?'':' locked');card.innerHTML='<div class="ico">'+(have?item.emoji:'❔')+'</div><strong>'+(have?item.name:'Hidden charm')+'</strong><span class="rare '+item.rare+'">'+(have?item.rare:'keep playing')+'</span>';box.appendChild(card);});}
function bind(){document.querySelectorAll('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>{unlockAudio();const id=btn.dataset.screen;if(id==='learn')renderLessons();if(id==='garden')renderSongs();if(id==='chest')renderCollection();show(id);}));document.getElementById('q-lines').addEventListener('click',()=>startQuiz(LINE_NOTES,'Line notes'));document.getElementById('q-spaces').addEventListener('click',()=>startQuiz(SPACE_NOTES,'Space notes'));document.getElementById('q-mix').addEventListener('click',()=>startQuiz(STAFF_NOTES,'Whole staff'));document.getElementById('q-all').addEventListener('click',()=>startQuiz(ALL_NOTES,'Balcony notes'));document.getElementById('open-chest').addEventListener('click',()=>openChest(false));document.getElementById('sheet-close').addEventListener('click',()=>document.getElementById('modal').classList.remove('show'));document.getElementById('hear').addEventListener('click',()=>{if(quiz&&quiz.noteId)playFreq(NOTES[quiz.noteId].freq,0.7);});document.getElementById('save-name').addEventListener('click',()=>{const value=document.getElementById('name-input').value.trim();if(value)state.name=value.slice(0,18);save();document.getElementById('modal').classList.remove('show');});document.getElementById('grownups').addEventListener('click',()=>{document.getElementById('name-input').value=state.name;openSheet('Grown-ups',"Progress stays on this iPad. Add the site to the Home Screen from Safari's Share button.",'🌷');});document.getElementById('reset').addEventListener('click',()=>{if(!confirm('Reset stars, songs, and charms on this device?'))return;localStorage.removeItem('note-castle-v1');location.reload();});}
document.getElementById('name-input').value=state.name==='Princess'?'':state.name;paintStars();renderLessons();renderSongs();renderCollection();bind();show('home');
